### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by jhchen** [comment]
Why should it be removed though? It still provides accurate version info for the end user.

**Comment by kkirsche** [comment]
Considering bower core dev is basically dead and the recommendation is to use NPM instead of Bower, users shouldn't be encouraged to continue using a mostly dead product where core development has slowed and is essentially dead

**Comment by jhchen** [comment]
> the recommendation is to use NPM instead of Bower

Can you share the source for this? Not saying I disagree--bower was added in the early Quill days due to popular request rather than merit.

**Comment by kkirsche** [comment]
@jhchen the easiest link is just to the discussion to move Bower entirely under NPM bower/bower#1520

**Comment by jhchen** [comment]
I see. I'm going to keep the version field for now but thanks for the link.

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Pull request closed without merging**
