### PR TITLE
Add support for custom image handler

### LINKED ISSUE #90: Does quill support image upload?
Hi,
Quill is an excellent editor!!
May I know whether quill support image upload?any demo server side script?
Many thanks.

### PR DESCRIPTION
**Pull request by jackmu95**
This commit adds the ability to pass a custom image handler with the Quill options.

The handler takes a file object as first argument and a callback function as second. The callback function expects to be called with the result of the image processing.

**A custom image handler could look like:**

``` javascript
var imageHandler = function(image, callback) {
  var formData = new FormData();
  formData.append('image', image, image.name);

  var xhr = new XMLHttpRequest();
  xhr.open('POST', 'handler.php', true);
  xhr.onload = function() {
    if (xhr.status === 200) {
      callback(xhr.responseText);
    }
  };
  xhr.send(formData);
};

var quill = new Quill('#editor-container', {
  ...,
  imageHandler: imageHandler
});
```

Closes #90.

### CODE REVIEW

**Comment by w00fz** [comment]
I can see the value in this PR, to a degree, but is it really necessary to pollute the main quill scope for it? I also found myself having to change the image handler behavior but figured overriding the toolbar image handler was the quill way of doing it.

```
modules: {
    toolbar: {
        handlers: { ... }
    }
},
```

Perhaps a more modular way of managing handlers could be considered, that way handlers can be extended, overridden and have a better code and filesystem organization. In the case of this PR, one would be able to simply extend the ImageHandler, super the constructor and override just the method in charge of interpreting a File object.

**Comment by jackmu95** [comment]
Overriding the toolbar image handler does only change the behavior for inserting an image via the toolbar.

When you look forward to features like [image drag and drop](https://github.com/quilljs/quill/pull/822) and [image pasting](https://github.com/quilljs/quill/pull/821) support you should be able to see that a unified way for image handling is needed.

**Comment by daniplaninc** [comment]
Hi,

is there any news on when this feature might be added?

**Comment by 0x13a** [comment]
I'm waiting too for this thing, should I pull the commit brutally to my local version ? Thanks!! :)

**Comment by scottfr** [comment]
This seems like an important feature to improve Quill's image handling and a solid PR.

Any reason this can't be pulled in?

**Comment by cozzbie** [comment]
I thought this had been merged...already implemented in my code and was wondering why it wasn't working. :D

**Comment by cozzbie** [comment]
Just checked my version. The commit lines are present so I have the committed version. For some reason my imageHandler is never called.

```javascript

let imgHandler = (i, cb) => {
          console.log("Image handler called");
      }

      this.editor = new Quill('#editor', {
          modules: { toolbar: "#toolbar" },
            placeholder: 'you can start here and make it a blast...',
            theme: 'snow',
            imageHandler: imgHandler
      });

```

**Comment by jakelisby** [comment]
Having the same issue as @cozzbie with the handler never being called.

**Comment by cozzbie** [comment]
I have an implementation now works...kinda.

```javascript
this.editor = new Quill('#editor', {
      modules: { toolbar: "#toolbar"},
      placeholder: 'you can start here and make it a blast...',
      theme: 'snow'
});

this.editor.getModule("toolbar").addHandler("image", imgHandler);
```
Your `imgHandler` will get called but you might have to write your own implementation of how files are selected

**Comment by crizant3908** [comment]
@cozzbie This is the default way you attach handlers, but not with the implementation which @jackmu95 did.

**Comment by CallMEJun** [comment]
@cozzbie thx  !!  I combine yours with official document and it's ok.

**Comment by rickyk586** [comment]
There's a link to a codepen here where you can download a minified js with this pull request: https://github.com/quilljs/quill/issues/1089

**Comment by Humni** [comment]
The lack of ability to add attributes to the image when it is inserted could be problematic for situations where you might want a "max-height" by applying a class or a aligning the image. Adding another parameter to the callback so it was more along the lines of

**Comment by Humni** [comment]
The lack of ability to add attributes to the image when it is inserted could be problematic for situations where you might want a "max-height" by applying a class or a aligning the image. Adding another parameter to the callback so it can take attributes for the Delta creation would be very benificial

**Comment by jasonlbw** [comment]
@jackmu95 it can't work at master?i install it at npm,but it can't work,how can i do?

**Comment by KonstantinShkut** [comment]
Any updates on when this will be merged in?

**Comment by hqt** [comment]
Can we merge this PR. This is an important feature that I think QuillJS should add.

**Comment by HugsDaniel** [comment]
Hi guys and gals, wondering if you had any news on this one ? I'm trying to implement my custom image handler and I have a bit of trouble. This PR looks cool :v:

**Comment by WilcoM** [comment]
Would love to see this merged. Please consider.

**Comment by jackmu95** [comment]
Closed. Quill v2 will support this.

**Comment by jackmu95** [comment]
@WilcoM I suggest to create you own toolbar handler for now:
```js
const quill = new Quill('#editor', {
  toolbar: {
    handlers: {
      image: function() {
        let fileInput = this.container.querySelector('input.ql-image[type=file]');
        if (fileInput == null) {
          fileInput = document.createElement('input');
          fileInput.setAttribute('type', 'file');
          fileInput.setAttribute(
            'accept',
            'image/png, image/gif, image/jpeg, image/bmp, image/x-icon'
          );
          fileInput.classList.add('ql-image');
          fileInput.addEventListener('change', () => {
            if (fileInput.files != null && fileInput.files[0] != null) {
              // Do your own stuff here
            }
          });
          this.container.appendChild(fileInput);
        }
        fileInput.click();
      }
    }
  }
});
```

**Comment by kyrofa** [comment]
> I suggest to create you own toolbar handler for now

@jackmu95, is your [previous comment](https://github.com/quilljs/quill/pull/995#issuecomment-255264832) on this matter invalid, then?

> Overriding the toolbar image handler does only change the behavior for inserting an image via the toolbar.
> 
> When you look forward to features like image drag and drop and image pasting support you should be able to see that a unified way for image handling is needed.

**Comment by Tunlier** [comment]
Why can't I get it to work? The image handler never get called.

Sorry I'm new in git conversations with all these merges or whatsoever. I'm using v1.3.6 from the cdn link.

**Comment by Tunlier** [comment]
How do I get it to work? @jackmu95 
This will be in v2 but what now? I'm confused, all these files in the repo. Which file(s) from where should I use?

**Comment by PaulleDemon** [comment]
@jacobmllr95 this doesn't call the image handler when drag and dropped image into editor

**Pull request closed without merging**
