### PR TITLE
Add image paste support

### PR DESCRIPTION
**Pull request by jackmu95**
This pull request adds basic image paste support as requested in #796.

### CODE REVIEW

**Comment by intdel** [comment]
Is there a reason why this got never merged?

**Comment by jhchen** [comment]
A general approach is still being discussed in #822. During the release candidate I did not want to add more features so will revisit a bit after 1.0 launch stuff is done.

**Comment by bradennapier** [comment]
+100 - this is the make or break feature for me personally! :)

**Comment by bladerunner41** [comment]
The default quill file upload toolbar, as well as the drag & drop module (`quill-image-drop-module`) all inline the image in base64, except copy & paste which uses an `` approach.  It should be consistent.  Example of pasting as base64 in #137

**Comment by jackmu95** [comment]
Closed due V2 changes.

**Pull request closed without merging**
