### PR TITLE
Added capability to add blob url images

### PR DESCRIPTION
**Pull request by didix16**
This adds the capability to add images with blob urls. #4207

### CODE REVIEW

**Comment by luin** [comment]
Thanks for the contribution! I think we can't support all protocols in the core as applications have different requirements. You should be able to extend the built-in `Image` format and override the `sanitize` method.

**Comment by didix16** [comment]
Hi, thanks for your reply.
I don't understand this:
> I think we can't support all protocols in the core as applications have different requirements 

If you add more functionality to the core,  aren't you improving the software? I mean, It becomes better in such way that It can handle more things and covers more needs.

That being said, how can I extend the Image module and override the sanitize function.

I think my contribution does that, right? I mean, I simply expanded the capabilities of the Image module.

Thanks.

**Comment by luin** [comment]
Yeah you can extend `Image` and register your own image module with `Quill.register()`.

> If you add more functionality to the core, aren't you improving the software? I mean, It becomes better in such way that It can handle more things and covers more needs.

Supporting more things is not always better - applications may not want `blob` at all just like some of them don't like `http`.

**Comment by didix16** [comment]
Mmmm I see.

So, to be able to extend Image to allow blob urls and register it to my Quill editor I must do something like this?
```js

import Image from 'quill/formats/image'
import { sanitize } from 'quill/formats/link';
import Quill from 'quill';

class MyImage extends Image {
    static sanitize(url) {
        return sanitize(url, ['http', 'https', 'data', 'blob']) ? url : '//:0';
    }
}

Quill.register('formats/image', MyImage)
```

Is that correct?

**Comment by luin** [comment]
Yes, that's the way to register a custom image. Here's an [example](https://quilljs.com/playground/snow#codeN4Ig9AlgdgJgpgDwHQCsDOIBcIDGAbAQzTQAIBZATwEkBbAgczhMQBc5ZSBFAVwjzyQQaABwD2AJxYAKAOQAzCXRZpIdRjICUJYAB0oJAyTQsCLCDiMEoEMwC84U7uLxbd+wwZyioaUXjhIeKL0sgC8oTjcxqI0JEIMcOGaeh4e4nAsTvpo3MJw4khoVjYQ9o7OADQkANoyABYsLMIyVfWNwmgtJDIwpgRdMgBGQYMyALpaAPwkTngkmN1gYJgADDIA3CmGAL56u1B6PHwC6fQQxvmyCuJKKvHqVZS0CRp6b1BePiwkAI68-CRQiQoHAAO4kI78WQAYjgMBsEi6bgMNFEMG4-jQC2RhhYoj8gwI4gW1S2HmqwBIdTgBHgxJqAEYqgAmKpyAh4NBwMYkbZjCpkwy1QZ+GADGwc8wDbiwfJ4aBwcYC9zkmT3RWtLzwAC0w1EOAA1krBfytttlQZhIQcHA6qL8gsZABhGJiLkkKzMYTmJC+lpbFjUmhwR1oKCiUFdJYkCTdQbcQbDRV7DTrEAVcDQeDIBo0PBYEAAHnhADc4jBQjoQHCEeIqwA+QtgUv196FtA4cQQYTfNDiHCVzOy5DoBtNjtdnv1kDbIA). Please provide a reproducible example if you encounter any issues.

**Pull request closed without merging**
