### PR TITLE
fix chrome 52+ input file label open slow

### PR DESCRIPTION
**Pull request by YouHan26**
reference: 
[chrome 52 slow](http://stackoverflow.com/questions/39187857/inputfile-accept-image-open-dialog-so-slow-with-chrome)
[input type MIME type](https://www.sitepoint.com/web-foundations/mime-types-complete-list/)

### CODE REVIEW

**Comment by jhchen** [comment]
Thanks!

**Comment by benbro** [comment]
image/x-icon, image/x-quicktime are standard images?
Isn't image/svg missing from the list?

**Comment by jhchen** [comment]
x-icon is for favicons. Wasn't sure about x-quicktime but the argument could be make image/* accepted it as well. Forgot about svgs so I will add this into the list and probably delete x-quicktime too.

**Comment by YouHan26** [comment]
x-quicktime isn't  for ios quicktime? I'm not sure about this because I'm a Windows user

**Comment by jhchen** [comment]
I've always associated Quicktime with videos so maybe this is one frame as an image or something. I have never seen a .qif, .qti, or .qtif file though.

**Pull request merged**
