### PR TITLE
clipboard fix

### PR DESCRIPTION
**Pull request by volser**
fix for https://github.com/quilljs/quill/issues/2706

### CODE REVIEW

**Comment by jhchen** [comment]
What's the test case for this?

**Comment by volser** [comment]
for example, to linkify pasted text

**Comment by volser** [comment]
added test https://github.com/quilljs/quill/pull/2707/files#diff-e3c26167d5897539716a67d518afd55dR343

**Comment by jhchen** [comment]
I more meant how is this encountered ex steps for reproducing this issue: https://github.com/quilljs/quill/blob/develop/.github/ISSUE_TEMPLATE.md. I'm not aware that browsers just omit text/html

**Comment by volser** [comment]
visit:
https://codepen.io/volser/pen/dxgoKw

steps:
https://recordit.co/4RfdMYuQET

**Comment by jhchen** [comment]
There's a bug in urlMatcher in the codepen where Delta is not defined. If you add a console.log you can see the function is getting hit. When you have a verifiable reproducible case, please review the contributing guide and follow the issue template to submit an Issue first.

**Comment by volser** [comment]
@jhchen sorry, but I don't see console log, when paste from text
https://recordit.co/ooYLoyPP7d

**Comment by volser** [comment]
@jhchen did you see last video?

**Pull request closed without merging**
