### PR TITLE
Fix: Typo (Quill 1.0 -> Draft 1.0)

### PR DESCRIPTION
**Pull request by 1c7**
https://quilljs.com/guides/comparison-with-other-rich-text-editors/#draft
image

### What this PR do?
fix a small typo in doc
image

Thanks

### CODE REVIEW

**Comment by benbro** [comment]
It should say:
```
Prior to Quill 1.0, Quill allowed...
```

**Comment by 1c7** [comment]
@benbro  oh, you are right, thanks

**Comment by 1c7** [comment]
let me send a new PR

**Comment by 1c7** [comment]
new PR here: https://github.com/quilljs/quill/pull/2219

**Pull request closed without merging**
