### PR TITLE
Add touchstart listener if touchstart event is supported else add click listener. but do not add both.

### PR DESCRIPTION
**Pull request by sferoze**
Add touchstart listener if touchstart event is supported else add click listener. but do not add both.

### CODE REVIEW

**Comment by sferoze** [comment]
@jhchen 

I was thinking about this and I am wondering something. Is there ever a case where `touchstart` is supported by a device, and also `mousedown` is supported? 

Maybe like the Surface? Which has a touch screen but also uses a mouse. I am not sure how that device handles it, but if touchstart is supported, you have to touch the screen to check the box. As the click listener is not added. 

Maybe this is more appropriate?

```
domNode.addEventListener('mousedown', listEventHandler);
domNode.addEventListener('touchstart', listEventHandler);
```

If we use mousedown instead of the click event, it will not be called twice as the mouse and touch events are completely seperate. 

Is this a better route or is the commit I have the better route? All depends on how something like the surface handles this... which I am not sure about.

**Comment by jhchen** [comment]
Yes I suppose any device with an external keyboard would have this. Let's go with the mousedown then?

**Comment by sferoze** [comment]
@jhchen I made a new commit with both mousedown and touchstart event added

**Comment by jhchen** [comment]
Thanks!

**Pull request merged**
