### PR TITLE
Fix blockembed selection

### PR DESCRIPTION
**Pull request by guillaumepotier**
Hi there,

Thanks to @benbro in #1740, I finally managed to get Quill working in my build pipeline, and here is my first PR here 🎉 

This is related to #1720 : when you have rich elements (let's say a complex React element that is inserted inside a quill BlockEmbed blot) and you do something **inside** them (writing in a textarea, an input, etc..), Quill keeps a wrong selection that induce many problems (focus, scroll, etc..) during collaboration with others.

This PR aim is to clear Quill selection when the user clicks on a BlockEmbed element (Philosophy is, even if the BlockEmbed is inside Quill root element, it should be inert, inactive like if we were somewhere else on the page but in the editor).

I basically made two changes:

- in `blots/block/embed` (or `BlockEmbed` blot), I've added a DOM attribute `data-blockEmbed="true"` to distinguish in the DOM that we are dealing with a block embed element
- in `core/selection` I added a test that checks if the current selection is **inside** a BlockEmbed, and if so, it returns `null` like if we were outside the root container

I updated the tests to add `data-blockEmbed` but did not added new tests to ensure this behaviour.

Please, let me know If you have any feedbacks or thoughts about this PR, I'd be glad to quickly help (as I desperately need this PR to fix many collaboration issue I have in my project :) )

Best

### CODE REVIEW

**Comment by jhchen** [comment]
Hey @guillaumepotier thanks for the PR! There is a lot of code to just detect a block embed and it also involves marking. Second it does not fix the issue for inline embeds. Is there a simpler way to address the root problem?

**Comment by guillaumepotier** [comment]
Hi,

Thanks for your answer.

> Second it does not fix the issue for inline embeds

You're right. I hesitated and did not manage to understand clearly the difference bw inline embeds and block embeds. I also asked myself if they should have the same behaviour.

If we do not want to involve markup, IMO we should put the test in [normalizedToRange](https://github.com/quilljs/quill/blob/develop/core/selection.js#L185) and test if one of the two bounds is an embed/blockembed. I first went for this solution and found it may come a bit late in the code.

I'd be glad to modify and re-implement this last solution if it sounds better to you.

WDYT?

Best

**Comment by jhchen** [comment]
I think the first step is providing a failing test case so we can quickly try different implementation solutions and verify they work. One place it could go is test/unit/blots/block-embed.js.

**Comment by soccerloway** [comment]
@guillaumepotier Hi,
thanks for your solution. It makes my embed blot within editable element work well.
But the cursor will be unpredictable if I press arrow left to select a embed blot, because `getNativeRange` will `return null`, and causing `listen` function of **modules/keyboard** return.
and the cursor position will be unexpected. 
I'm not sure that if I missed any details of your solution?

**Pull request closed without merging**
