### PR TITLE
Handle text replacements explicitly

### PR DESCRIPTION
**Pull request by luin**
Fixes: https://github.com/quilljs/quill/issues/3692, https://github.com/quilljs/quill/issues/3375, https://github.com/quilljs/quill/issues/2407, https://github.com/quilljs/quill/issues/2096, https://github.com/quilljs/quill/issues/3692 , https://github.com/quilljs/quill/issues/3375 , https://github.com/quilljs/quill/issues/2407 , https://github.com/quilljs/quill/issues/2096 , https://github.com/quilljs/quill/issues/3267 , https://github.com/quilljs/quill/issues/2187 , https://github.com/quilljs/quill/issues/2285 , https://github.com/quilljs/quill/issues/2144 , https://github.com/quilljs/quill/issues/3522 , https://github.com/quilljs/quill/issues/2498 , https://github.com/quilljs/quill/issues/3450 , https://github.com/quilljs/quill/issues/3711

In the case of text replacements (see definition below), we currently rely on the browser's default behavior and then utilize MutationObserver to synchronize DOM changes with the model. Sometimes, this approach doesn't work well, as browsers may generate unexpected mutations that Quill is unable to process.

At Slab, we handle text replacements explicitly with Input Event (mostly Level 1 but some Level 2 features supported by all modern browsers) and it's been working reliably for months. This PR mostly moves the code to Quill but also handles IME as well.

## Definition of Text Replacements
The most common scenario occurs when a range of text is selected, and the user presses any keystrokes.

Additionally, built-in spell checks and some platform-specific operations (e.g., emoji picker, text replacement settings on macOS) can also be considered as text replacements.

It's important to note that the selection does not necessarily need to encompass the text that is about to be replaced. For instance, on some platforms, there may be a hover toolbar that appears when the user moves the cursor over the misspelled word, allowing them to select a word to replace the current word.

## Test Plan

Open http://localhost:9000/standalone/full.

### Simple text replacement

Enter "abc" and make "b" red. Select "bc" and press "d". Make sure the editor ends with "ad".

### Simple text replacement with IME

Enter "abc" and make "b" red. Select "bc". Switch to a Chinese/Japanese IME, press "d" and confirm the word. Make sure "bc" is replaced by the confirmed word.

### Spell check

Enter "a makeing" and make "makeing" red. Right-click on "makeing" and select "making" in the spell check list:

CleanShot 2023-06-22 at 17 47 47@2x

Make sure "makeing" is converted to "making", and "making" is in red.

### Others

Make sure the mentioned issues are fixed.

---

I verified all the mentioned issues except https://github.com/quilljs/quill/issues/2407 which I can't reproduce on my side and this PR fixes all of them.

I also tested on the following browsers and all seem to work correctly:

1. Safari 15 on macOS 12
2. Safari 16 on macOS 13
3. Chrome on Android API 34
4. Safari 16 on iOS 16.5.1
5. Firefox: 89 on macOS 10.15
6. Chrome 114 on macOS 13
7. Chrome: 99 on macOS 10.15

## TODO items

- Support Android devices.
- I believe we can extend the Input module to handle more input types while also transferring some logic from the Keyboard module to the Input module. For instance, we could move the `handleBackspace` function to the Input module by handling the `deleteContentBackward` input type. This improvement would increase compatibility with system features, such as iOS's dictation.

### CODE REVIEW

**Review by jhchen — APPROVED** [review]

**Comment by fnlctrl** [comment]
(Sorry if this is out of scope of this PR, I can create a separate issue if that's the case)

In https://github.com/quilljs/quill/issues/2096 which is closed by this PR, a comment https://github.com/quilljs/quill/issues/2096#issuecomment-399576957 mentioned the handling of `<font>` elements as a workaround.

It seems that there's another case where `<font>` is inserted when typing with Chinese IME: typing on an empty line that has an empty inline element with `<br>` that holds the styling. This is native contenteditable behavior and is observed on both Chrome and Safari, and there seems to be no way to prevent it. In Quill, it causes content to be removed unless a `<font>` blot is registered. 

Reproduction: 
1. create an html file with the following content, or open [this fiddle](https://jsfiddle.net/4tqhje39/1/) 
```html
<!DOCTYPE html>
<html>
  <body>
    <div class="ql-editor" contenteditable="true" spellcheck="true">
      <p style="font-size: 18px">
        <strong style="color: rgb(0, 128, 0); font-size: 18px"
          >Styled paragraph (empty line below)</strong
        >
      </p>
      <p style="font-size: 18px">
        <strong style="color: rgb(0, 128, 0); font-size: 18px"><br /></strong>
      </p>
      <h1>List item</h1>
      <ol>
        <li>
          <span class="ql-ui" contenteditable="false"></span>
          <span style="color: rgb(102, 204, 132); font-size: 36px"
            >List with inline style (empty line below)
          </span>
        </li>
        <li>
          <span class="ql-ui" contenteditable="false"></span>
          <span style="color: rgb(102, 204, 132); font-size: 36px">
            <br />
          </span>
        </li>
      </ol>
    </div>
  </body>
</html>
```

2. Select the empty `<br>` in browser inspect menu, type "a" "f" "c" on the empty line

3. Observe that a `<font>` element is inserted

Gif recording:
Chrome:
chrome

Safari:
safari

**Comment by luin** [comment]
I don't feel it's possible to have `br` wrapped with `strong`. Is there a way to reproduce that programmatically?

**Comment by fnlctrl** [comment]
@luin Yes, though it's not the default behavior of quill (but it's a hack to restore the native contenteditable behavior)

Demo: https://stackblitz.com/edit/vitejs-vite-bcjsis?file=main.js&terminal=dev

Long story short, one tiny but critical missing behavior of quill (or any other editors like tiptap/prosemirror etc.) that makes it inferior to the experience of Google Docs, is inheriting inline styles from previous lines when hitting enter at the end. Quill's cursor implementaion can only retain formats for the current line. The hack in the demo tries to mimic Google Docs' behavior

Google Docs behavior: 


Vanilla quill behavior:


Hack in the [demo](https://stackblitz.com/edit/vitejs-vite-bcjsis?file=main.js&terminal=dev)


This hack is an approximation because it doesn't really persist the formats on empty lines. They get filtered out by quill.getContents(), but they survives reloads because inheriting styles from previous blocks is deterministic. It all works intuitively - until IME comes into play that breaks it apart.

I do consider the behavior of using `<br>` as placeholder to be correct, because it's exactly how native contenteditable retains formats for empty lines: It copies the styling, and adds a `<br>` to the empty <span>


If we can fix the `<font>` issue, then final piece of the puzzle would be actually persisting the empty line formats to Delta. It could work by allowing line breaks (blocks) to use inline-level attributes, e.g.
```js
{ 
  insert: '\n', 
  attributes:  {
    color: '#569cd6',
    size: '18px',
    bold: true,
    underline: true,
    italic: true
  }
} 
```
This would represent the empty line that holds the default inline formats.

**Comment by luin** [comment]
Okay I think that makes sense. Can you create a new ticket for that? I think a way to fix that is to listen to compositionstart when caret is at the beginning of a formatted empty line, and reset the br styles. Also listen to compositionend and restore the styles. Haven't thought about it thoroughly though.

**Comment by fnlctrl** [comment]
We discovered that `<font>` insertion can be avoided if the empty line is held up by an empty space instead of a `<br>`. We managed to fix this by replacing the empty `<br>` with a space on `compositionstart`, and removing the space by manipulating DOM directly on `compositionend`. This seems to work well with undo/redo.

**Comment by luin** [comment]
@fnlctrl Have you tried utilizing `beforeinput` event? By capturing `beforeinput`, you can take over the text insertion and apply inline attributes there:


https://github.com/quilljs/quill/assets/635902/ccd2648e-ebbc-454b-ad61-ff59c84939ed

Code: https://github.com/quilljs/quill/compare/zh-emptyline-formats?expand=1

There are still some TODOs left though:

1. Toolbar button status
2. IME support. Safari and Firefox support insertFromComposition, which should make IME support easier.

**Pull request merged**
