### PR TITLE
Refactors embedded youtube link regex

### PR DESCRIPTION
**Pull request by ygrishajev**
So mobile link like 'http://m.youtube.com/...' can be embedded

### CODE REVIEW

**Comment by ygrishajev** [comment]
**Just some detailed explanation of the issue that is fixed by this pull request:**

Youtube link differ for its mobile version: 'https://m.youtube.com/...'. So when such link is pasted into video embed tooltip an error is thrown:

`Refused to display 'https://www.youtube.com/watch?v=...&app=desktop' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`

**Steps for Reproduction**

1. Visit [quilljs.com]
2. Try to embed youtube video (e.g. https://m.youtube.com/watch?v=IyTv_SR2uUo)
3. See console errors

**Expected behavior**:
1. Video is embedded properly
2. No console errors

**Actual behavior**:
Error is thrown

**Platforms**:
IOS, OSX

**Version**:

1.1.5

**Comment by jhchen** [comment]
Can you include tests? This regex is getting unwieldy with additional forms of YouTube links it is expected to support.

**Comment by benbro** [comment]
This is based on [StackOverflow](http://stackoverflow.com/a/9102270):
```javascript
var reg = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([a-zA-Z0-9_-]+).*/;
var match = url.trim().match(reg);
if (match && match[2].length == 11) {
 value = 'https://www.youtube.com/embed/' + match[2] + '?showinfo=0';
}
```

**Comment by stalniy** [comment]
@jhchen Hi, could you please tell where you would like these tests to be in `test/` folder?  `https://github.com/quilljs/quill/blob/develop/test/unit/blots/block-embed.js`  or a separate file for like `test/unit/theme/base.js`

**Comment by stalniy** [comment]
@jhchen could you please answer the question above? It's critical for me to have this and I can finish the pull request (i.e., add tests)

**Comment by jhchen** [comment]
In terms of file organization it should probably go in theme/base.js since that is what is being tested. There may need to be some refactoring of the source code to enable unit testing which may influence which test/ folder or file it goes into.

**Comment by weavermedia** [comment]
We're currently running into this issue. Is there anything blocking this merge?

**Comment by stalniy** [comment]
As a workaround you can create own theme which extends SnowTheme and monkey patch Tooltip. This is what I did

**Comment by stalniy** [comment]
@ygrishajev you can close this. The work was finished in #1489

**Pull request closed without merging**
