### PR TITLE
Fix typo: Draft -> Quill

### PR DESCRIPTION
**Pull request by 1c7**
image

### CODE REVIEW

**Comment by benbro** [comment]
Thanks!

**Comment by jhchen** [comment]
I don't think this was a typo. It is supposed to discuss the customization of Draft but once Quill 1.0 was released they become on similar footing.

**Comment by benbro** [comment]
Sorry, I merged the fix.

**Comment by jhchen** [comment]
No worries -- easy enough to revert. Thanks for taking a look!

**Pull request merged**
