### PR TITLE
fix script tag markdown

### PR DESCRIPTION
**Pull request by kotAPI**
The script tag and it's content wasn't displaying properly

fixed the markdown syntax to display correctly on README

### CODE REVIEW

**Comment by jhchen** [comment]
Did you try this to see what it does? I don't think it has a desirable outcome.

**Comment by kotAPI** [comment]
This is how it looks right now and I corrected the markdown syntax.

https://github.com/quilljs/quill/blob/develop/docs/docs/modules/toolbar.md

Sorry for the wrong PR if this doesn't have a desirable outcome.. :)

**Comment by jhchen** [comment]
Where are you seeing this? It kind of looks like the homepage but the colors are different. If it is your local environment then there is probably a misstep in your build.
screen shot 2018-02-05 at 11 50 15 pm

**Comment by kotAPI** [comment]
Here, to the end of the document

[toolbar.md](https://github.com/quilljs/quill/blob/develop/docs/docs/modules/toolbar.md)

**Comment by kotAPI** [comment]
Also the `{% include full-toolbar.html %}` in the starting of the README document, not sure if it's supposed to be there? :)

**Comment by jhchen** [comment]
I mean where as in the URL. The website https://quilljs.com/docs/modules/toolbar/ shows the dark syntax highlight I showed, so I assume not there.

**Pull request closed without merging**
