### PR TITLE
use DOMParse in pasteHTML to protect against dangerous html

### PR DESCRIPTION
**Pull request by benbro**
fix https://github.com/quilljs/quill/issues/981

### CODE REVIEW

**Comment by benbro** [comment]
Only tested with Firefox 48.

**Comment by jhchen** [comment]
It seems to have not passed the unit test for Chrome+Firefox on all operating systems.

**Comment by benbro** [comment]
Is it possible that it's something specific to the tests?
Maybe something in initialize?
https://github.com/quilljs/quill/blob/develop/test/helpers/unit.js#L104
Not sure what's the difference because initialize just set the container's html.

Testing with this PR produce the correct delta when using:
```html
<div class="standalone-container">
  <div id="snow-container"><p class="ql-align-center">Test</p></div>
</div>
```

Assuming that it'll work, do you want to use DOMParser or close the PR?
I think it's different from dangerouslySetInnerHTML in React because Quill use Delta which I think are safe.
Only way pasteHTML was unsafe.

**Comment by jhchen** [comment]
If DOMParser works without issue it would be a good idea to use it. I do not want to rename back to pasteHTML though. I want to set the expectation that the HTML you hand Quill should already be safe, and while Quill should do things safely itself, it is not the security solution to unsafe input.

**Comment by benbro** [comment]
Do you have a suggestion about the failing tests?

**Comment by jhchen** [comment]
It looks like the reason is `getComputedStyle` cannot be used. Quill uses this to figure out where to place newlines and sometimes when applications paste HTML that contain classes and `<style>` tags.

**Comment by benbro** [comment]
I see. This example gives me:
'inline' in Firefox 49 on Windows 7
empty string on Chrome 53 on Windows 7
http://codepen.io/anon/pen/EgWRrV

**Comment by jhchen** [comment]
In light of this I'm not seeing a way to use DOMParser.

**Comment by benbro** [comment]
Thanks

**Pull request closed without merging**
