### PR TITLE
fixed possible NPE

### PR DESCRIPTION
**Pull request by denis-aes**
simple one line change to avoid possible troubles

### CODE REVIEW

**Comment by benbro** [comment]
What is NPE?
Please explain the change and steps to reproduce the issue it solves.

**Comment by denis-aes** [comment]
@benbro NPE is null pointer exception. 

Code was
```
let index = range.index + range.length;
         if (range != null) {
```          
That's really strange. First we are attempting property from object "range" and next line we are checking this object is not null.

I would expect that we should check object for null first, and only after this try to get it properties. So made
```
         if (range != null) {
let index = range.index + range.length;
```

index variable is used only inside if. Please, take a look at diff. It's really simple.

**Comment by benbro** [comment]
Updated my comment.
Thank you for the explanation.

**Comment by denis-aes** [comment]
@benbro thank you too

**Comment by jhchen** [comment]
Thanks guys!

**Pull request merged**
