### PR TITLE
Fix link tooltip

### PR DESCRIPTION
**Pull request by thomsbg**
A collection of small changes to the link-tooltip module. All are teensy UX improvements my users have asked for after some experience using quill.

### CODE REVIEW

**Comment by jhchen** [comment]
Thanks for the PR. The only issue is the anchor tag to normalize urls. The main purpose of the function (which now seems poorly named) is a minor protection against xss rather than fix malformed urls so at minimum the check for whitelisted protocols should remain. Using the anchor seems unnecessary as the url is set to the href of another anchor (either the link being modified or the one being created) later anyways. Can we remove that commit and I'll merge the other three?

**Comment by thomsbg** [comment]
I added that href normalization after seeing this bug:

* Select text and click link tooltip button
* Enter `http://google.com` into the input and click `Done`
* The resulting url is `http://google.com/` (trailing slash)
* Click change, input value still has `http://google.com` (no trailing slash)
* Click done, the resulting markup is now `<a href="http://google.com"><a href="http://google.com/">text</a></a>`

This wasn't a problem before, because the tooltip used to close immediately upon clicking `Done`.

I suspect this was happening because the `linkFormat.value()` was returning the url with a trailing slash, so calling `linkFormat.add('http://google.com')` doesn't match the current value and ends up wrapping the whole thing in another `<a>` tag.

Perhaps a different solution to this problem would be to reset the value of the input after clicking `Done`?

**Comment by jhchen** [comment]
Yes resetting the input and repopulating would be better so we can avoid maintaining the extra anchor.

**Comment by thomsbg** [comment]
Ok, I've refactored to use the existing `@link` element to do the url normalization, as well as addressing a few bugs that had come up. Sorry for the ongoing work in a pull-request branch, I usually try to avoid that.

**Comment by jhchen** [comment]
Thanks!

**Pull request merged**
