### PR TITLE
Update #toEqualHTML matcher to check structure before nodes.

### PR DESCRIPTION
**Pull request by RyanV**
see https://github.com/quilljs/quill/issues/2241.

@jhchen this test now correctly fails.  This code change will be necessary to write a proper test for https://github.com/quilljs/quill/issues/2195

I chose to keep the same toEqualHTML matcher, but to run a basic string match on the html structure first before comparing the DOM through parsing.

### CODE REVIEW

**Comment by RyanV** [comment]
Fixed bug in type stack causing failing test.  This should also fix https://github.com/quilljs/quill/issues/2195

**Comment by RyanV** [comment]
@jhchen Can you take a look at this one please? thanks!

**Comment by jhchen** [comment]
Thanks for identifying this issue. I preferred a smaller change https://github.com/quilljs/quill/commit/d54d2d00483068e6ca17d0aab3d0073bbe45f3d8 that is now in develop

**Comment by RyanV** [comment]
@jhchen actually, this still doesn't solve the problem.  you still have false positives being reported.

'<ul><li>foo</li><ol>'.length === '<ul><li>foo</li><ul>'.length which is not correct.  Your fix only checks the string length and reports false positives for the nested list test.

The fix to the editor.js code is also a necessary code change.

**Comment by jhchen** [comment]
Commenting in one place is enough. Please do not duplicate content in the future.

That is just a heuristic on the first pass to detect the reported issue of the browser "fixing" the markup. The rest of the function still runs which will check for tag equivalence. You can see neither
`expect('<ul><li>foo</li><ol>').toEqualHTML('<ul><li>foo</li><ul>');` nor does `'<ol><li>foo</li></ol>'`.

You can see the change to editor.js was made https://github.com/quilljs/quill/commit/c712420aa433fa7c4e1116403f98844112f6fe87

**Comment by RyanV** [comment]
Sorry, I honestly wasn't sure where the best place to put the response since it was marked "closed" so i threw some lines out.  In the future I'll just post in one place and only follow up if I don't get a response.

You can see how the change in https://github.com/quilljs/quill/commit/d54d2d00483068e6ca17d0aab3d0073bbe45f3d8 does _not_ cover the false positive case by running `test/unit/core/editor.js` for `nested list` test.  If you revert the change in https://github.com/quilljs/quill/commit/c712420aa433fa7c4e1116403f98844112f6fe87 (which causes the markup to return incorrect closing tags), you should expect the test to fail, but instead it still passes.  

I wrote _this_ implementation by ensuring that this test failed initially, then passed when the change in https://github.com/quilljs/quill/commit/c712420aa433fa7c4e1116403f98844112f6fe87 was applied.

**Pull request closed without merging**
