### PR TITLE
Added information about security when using quill to readme

### PR DESCRIPTION
**Pull request by woverton**
See: https://github.com/quilljs/quill/issues/510#issuecomment-152192649

### CODE REVIEW

**Comment by jhchen** [comment]
I'm all for being helpful to beginners but this is waaaayyyy too general. Sanitizing user input is on the top of most general web security guidelines and has nothing to do with Quill specifically.

**Comment by woverton** [comment]
I listed an example of how using quill in a form with no verification could be dangerous and then listed sanitization libraries which work with quill for multiple languages. 

I was not 'waaaayyyy' to general. If you're going to have an attitude when you don't directly agree with pull request, do it yourself :angry:.

I was only trying to improve the user friendliness that other text editors offer, see: http://www.tinymce.com/wiki.php/TinyMCE3x:Security. Less experienced developers will not immediately understand the problem with using quill and taking its output and directly showing it to other users.

**Comment by jhchen** [comment]
TinyMCE posted that page years ago when best web security practices were not well understood. Today sanitizing input specifically on the back end is well established guidance for any input, whether it's a JS library or a native textbox. Posting a warning on Quill specifically would only serve to confuse people, as it already did on the issue discussion. Furthermore it adds to the cost of maintenance of the particular list of sanitization libraries.

Open source is not about thousands of developers banging on keyboards and merging their efforts so everyone can feel good about contributing. If you want to be a part of it I suggest you grow thicker skin. Not every idea you have will be welcomed under scrutiny of others. Hopefully there will be some that are and that's where the focus should be.

**Comment by brettimus** [comment]
Serenity everyone!

William, I can see Jason's point where this might be too general for the
readme.

Is there a "quill for beginners" blog post already? This kind of advice
could make good material for the quill blog.

Let's all be friends! 💫🎉😁

**Comment by woverton** [comment]
@brettimus  You cant tell me what to do!

Angry

I expect a lot of developers wouldn't be checking out the blog post, but a quick head nod in the right direction would be just as useful.

**Comment by brettimus** [comment]
Hahahaha

**Pull request closed without merging**
