### PR TITLE
(docs update) clearify container types, polish code format

### PR DESCRIPTION
**Pull request by SergioCrisostomo**
- clearify that `container` property can be a DOM element
 - add code sintax tags

### CODE REVIEW

**Comment by jhchen** [comment]
Have you tried these changes out locally to see their effects?

**Comment by SergioCrisostomo** [comment]
@jhchen this is a docs polich/change. Only changes made to the `.md` file. 

Travis fails because it has random problems with starting up browsers. I should have used `[ci skip]` in the commit message.

If someone from the team can re-start those failing tests it will be green soon.

**Comment by jhchen** [comment]
HTML is being executed in order to embed the demo. Adding the code back ticks therefore is not just a cosmetic change.

**Comment by SergioCrisostomo** [comment]
@jhchen were do I find the demo that uses code from this page? Guide me on how to double check.
Otherwise specs run green, and this change makes visible code that was not showing up as docs.

**Comment by jhchen** [comment]
It is inlined in the page you are changing. Please set up a local dev environment https://github.com/quilljs/quill/blob/develop/.github/DEVELOPMENT.md run your changes and observe the difference between what you think your code does and what it actually does.

You are literally submitting code requesting it to be deployed without once running it.

**Comment by SergioCrisostomo** [comment]
Thanks for the input. 
I see and can run the demos, functional and unit. They pass. 
I can start up the dev server and run the demos in the `standalone` folder.

My question still is: how do I run demo for the toolbar? The `modules/toolbar.md` file I propose to change in this PR is not accepted as url in the tests. 

If there is a test where the code in this `.md` file is used I did not found it.

**Pull request closed without merging**
