### PR TITLE
Color picker rgb values

### LINKED ISSUE #917: Text Color Toolbar button doesn't display selected color when using a custom color list
If you manually create the font color list for your toolbar, the toolbar button will display the initially selected color. 
But if you then change the color through the toolbar, the toolbar button will revert to display the color as grey as soon as you type a character. The typed text does still use the correctly selected color however.

**Steps for Reproduction**

1. Visit http://codepen.io/jasongiss/pen/BLyRQm
2. Notice that the initially selected color (green) is displayed in the toolbar button, and stays as you type.
3. Change the font color using the toolbar button - notice that the new color is now displayed on the toolbar button.
4. Open the font color droplist - notice that the currently selected color isn't drawn as selected (with a black box around it).
4. Type a character - the toolbar button reverts to a grey color.

**Platforms**: Chrome 52 on Mac 10.11.6

**Version**: 1.0.0-rc4

### PR DESCRIPTION
**Pull request by jackmu95**
This commit adds support for RGB values and HEX values with capital letters in color picker.

Closes #917 #950 #966.

### CODE REVIEW

**Comment by jackmu95** [comment]
I have updated my initial approach to a more efficient one and support even more color formats.

**Supported formats:**
  - `#ff0000`
  - `#FF0000`
  - `rgb(255,0,0)`
  - `rgb(255, 0, 0)`

**Comment by jhchen** [comment]
The main issue with this implementation is it is leaking abstraction details from the picker. The toolbar should have no knowledge of the `<option>` values' and the fact that it is storing colors. I don't have a better solution but long term these practices make code hard to maintain.

**Comment by jackmu95** [comment]
@jhchen I'am with you that this implementation isn't perfect but it was the only solution I could came up with until now.

**Comment by benbro** [comment]
Can you fix the value in the [color format](https://github.com/quilljs/quill/blob/develop/formats/color.js#L6) instead?

**Comment by jackmu95** [comment]
The value for the color format is fixed to HEX values.

What about normalizing the color values in the [color picker](https://github.com/quilljs/quill/blob/develop/ui/color-picker.js#L15) to lowercase HEX values?

**Comment by nunoguerra** [comment]
What is the best way to add a input for user can put the custom color?

**Pull request closed without merging**
